name: evaluate
on: [push]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: cache source data
        id: cache-source-data
        uses: actions/cache@v3
        with:
          path: assets/source-data
          key: source-dataset

      # Download dataset
      - name: download source data
        if: steps.cache-source-data.outputs.cache-hit != 'true'
        env:
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        run: |
          pip install kaggle
          mkdir $HOME/.kaggle
          echo {"username":"$env:KAGGLE_USERNAME","key":"$env:KAGGLE_KEY"} > $HOME/.kaggle/kaggle.json
          kaggle datasets download -d fournierp/captcha-version-2-images

          mkdir -p assets/source-data/
          sudo apt-get install unzip
          unzip captcha-version-2-images.zip -d ./assets/source-data/

  train-model:
    runs-on: ubuntu-latest
    needs: pull
    steps:
      - name: checkout repo
        if: steps.cache-subsets.outputs.cache-hit != 'true'
        uses: actions/checkout@master  # cwd: /home/runner/work/ahri/ahri

      - name: cache source data
        if: steps.cache-subsets.outputs.cache-hit != 'true'
        id: cache-source-data
        uses: actions/cache@v3
        with:
          path: assets/source-data
          key: source-dataset

      - name: train model
        run: |
          docker build -q -t local .
          docker run --gpus all -it local python ./main.py
