name: evaluate
on: [push]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      # Download dataset
      - name: download source data
        env:
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        run: |
          pip install kaggle
          mkdir $HOME/.kaggle
          echo {"username":"$env:KAGGLE_USERNAME","key":"$env:KAGGLE_KEY"} > $HOME/.kaggle/kaggle.json
          kaggle datasets download -d fournierp/captcha-version-2-images

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-data
          path: captcha-version-2-images.zip

  build-dataset:
    runs-on: self-hosted
    needs: pull
    steps:
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          name: source-data

      - name: train model
        run: |
          7z x captcha-version-2-images.zip
          py build_dataset.py
          7z a dataset.7z train_dataset validation_dataset

      - name: Save dataset
        uses: actions/upload-artifact@v3
        with:
          name: dataset
          path: dataset.7z

  train-model:
    runs-on: self-hosted
    needs: build-dataset
    steps:
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          name: dataset

      - name: train model
        run: |
          7z x dataset.7z
          py main.py

      - name: trained model
        uses: actions/upload-artifact@v3
        with:
          name: trained-linear-svm
          path: assets/models
