name: evaluate
on: 
  workflow_dispatch:
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      # Download dataset
      - name: download source data
        run: |
          curl -LO https://github.com/AakashKumarNain/CaptchaCracker/raw/master/captcha_images_v2.zip

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-data
          path: captcha_images_v2.zip

  build-dataset:
    runs-on: self-hosted
    needs: pull
    steps:
      - uses: actions/checkout@v3
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          name: source-data

      - name: create dataset
        run: |
          7z x captcha_images_v2.zip -aos
          py build_dataset.py

      - name: Save dataset
        uses: actions/upload-artifact@v3
        with:
          name: dataset
          path: |
            train_dataset
            validation_dataset

  train-model:
    runs-on: self-hosted
    needs: build-dataset
    steps:
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          name: dataset

      - name: train model
        run: |
          7z x dataset.7z -aos
          py main.py
          7z a trained-neuron.7z assets -sdel

      - name: trained model
        uses: actions/upload-artifact@v3
        with:
          name: trained-neuron
          path: trained-neuron.7z

  test-model:
    runs-on: self-hosted
    needs: train-model
    steps:
      - name: Download dataset
        uses: actions/download-artifact@v3
        with:
          name: dataset

      - name: Download model
        uses: actions/download-artifact@v3
        with:
          name: trained-neuron

      - name: test model
        run: |
          7z x trained-neuron.7z -aos
          7z x dataset.7z -aos
          py test_model.py

      - name: result
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.txt

  deploy-mpdel:
      runs-on: self-hosted
      needs: test-model
      steps:
        - name: Download model
          uses: actions/download-artifact@v3
          with:
            name: trained-neuron
        - name: test model
          run: |
            7z x trained-neuron.7z -aos
      