name: evaluate
on: [push]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      # Download dataset
      - name: download source data
        run: |
          curl -LO https://github.com/AakashKumarNain/CaptchaCracker/raw/master/captcha_images_v2.zip

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-data
          path: captcha_images_v2.zip

  build-dataset:
    runs-on: self-hosted
    needs: pull
    steps:
      - uses: actions/checkout@v3
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          name: source-data

      - name: create dataset
        run: |
          7z x captcha_images_v2.zip -aos
          py build_dataset.py
          7z a dataset.7z train_dataset validation_dataset

      - name: Save dataset
        uses: actions/upload-artifact@v3
        with:
          name: dataset
          path: dataset.7z

  train-model:
    runs-on: self-hosted
    needs: build-dataset
    steps:
      - name: Download 
        uses: actions/download-artifact@v3
        with:
          name: dataset

      - name: train model
        run: |
          7z x dataset.7z -aos
          py main.py

      - name: trained model
        uses: actions/upload-artifact@v3
        with:
          name: trained-neuron
          path: assets/models
